services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:debug auth
    depends_on:
      - 'auth-mongo'
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
  tasks:
    build:
      context: .
      dockerfile: ./apps/tasks/Dockerfile
      target: development
    command: pnpm run start:debug tasks
    depends_on:
      - 'tasks-mongo'
    env_file:
      - ./apps/tasks/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  question-processor:
    build:
      context: .
      dockerfile: ./apps/question-processor/Dockerfile
      target: development
    command: pnpm run start:debug question-processor
    env_file:
      - ./apps/question-processor/.env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:debug notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
  schools:
    build:
      context: .
      dockerfile: ./apps/schools/Dockerfile
      target: development
    command: pnpm run start:debug schools
    env_file:
      - ./apps/schools/.env
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app
  auth-mongo:
    image: mongo:latest
    container_name: scholarly-auth-mongo
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
  tasks-mongo:
    image: mongo:latest
    container_name: scholarly-tasks-mongo
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27018:27017'
  notifications-mongo:
    image: mongo:latest
    container_name: scholarly-notifications-mongo
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27019:27017'
  schools-mongo:
    image: mongo:latest
    container_name: scholarly-schools-mongo
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27020:27017'
  rabbitmq:
    image: rabbitmq
    container_name: scholarly-rabitmq
    restart: 'unless-stopped'
    ports:
      - '5672:5672'
